INSERT INTO estudiantes(nombre,apellido,edad,email,seccion) VALUES
('Andres','Guzman',20,'3aZdH2@example.com','A'),
('Sergio','Guzman',30,'sergio2@pro12.com','B'),
('Gustavo','Tilix',20,'gustavo2@example.com','C'),
('Daniel','Pro',18,'daniel1@pro.com','A'),
('Sergio','Guzman',30,'sergio23@pro12.com','B'),
('Gustavo','Tilix',20,'gustavo12@example.com','C'),
('Maria','Angeles',20,'maria2@test.com','A'),
('Nicol','Perez',22,'nicol@test.com','B'),
('Eduardo','Luna',22,'eduardo@test.com','C'),
('Juan','Perez',28,'juan12@example.com','A'),
('Jorge','Termo',32,'jorge@example.com','B'),
('Soledad','Gusty',22,'soledad@example.com','C'),
('Belen','Gimenez',19,'belen@example.com','A'),
('Jordan', 'Vera',34,'jordan@example.com','B'),
('Catalina','Basan',25,'catalina@example.com','C');
